### ISSUE TITLE
Requests that fail cannot be retried

### ISSUE THREAD

**Issue by jgfaulk** [paulcbetts/Fusillade#14]
While testing my mobile app under bad network conditions, I noticed that if I make a request when a network connection is not available, an exception is thrown stating there is no internet connection as expected. However, if the network connection becomes available and I make the same request again the same exception is thrown no matter how many times I retry. 

I think this is because the operation that gets enqueued on lines 99 - 124 in RateLimitedHttpMessageHandler.cs does not handle network exceptions that may be thrown as a result of the call on line 99. Any exceptions thrown in this operation would cause line 123 to never run and therefore the in-flight response to never be removed. When the request is retried the same unique key is generated and the previously failed response gets returned.

**Comment by CliffCawley** [comment]
I can confirm that this happens for me too and was the cause of much frustration, till I realised it looks like RateLimitedHttpMessageHandler is caching the request even when there's an error. This was tested on Android. If you issue a request in flight mode, you can get a hostname not found error. Exiting flight mode and trying again results in the same error.

**Comment by stefandevo** [comment]
+1 for a fix of this issue?
@jgfaulk maybe you can make a pull request?

**Comment by jgfaulk** [comment]
Closing this since it is now merged into master
