### ISSUE TITLE
Update NuGet Package

### ISSUE THREAD

**Issue by jgfaulk** [paulcbetts/Fusillade#16]
The NuGet available on nuget.org does not include the critical #15 fix. Can someone update it? @paulcbetts? Thanks.

**Comment by CliffCawley** [comment]
I'm also interested in the nuget update with this fix. For now I will use source but would be great to have the update

**Comment by CliffCawley** [comment]
Although I'm using the source version (latest master) and it seems like the issue still exists.

**Comment by ghuntley** [comment]
@jgfaulk / @CliffCawley this is resolved in the release that just went out.

See https://github.com/paulcbetts/Fusillade/releases/tag/0.7.0 for release notes.
