### ISSUE TITLE
ModernHttpClient + PortableRest

### ISSUE THREAD

**Issue by arctouch-felipemomm** [paulcbetts/Fusillade#18]
Hi,

I noticed that Fusillade version 0.6 doesn't work with ModernHttpClient + PortableRest (Xamarin.Forms project), but adding the reference directly to Fusillade code works. Could you generate a new version for Fusillade since the latest one is from 2014?

Thanks,

**Comment by ghuntley** [comment]
0.7.0 has been released. Can you please try again now?

**Comment by arctouch-felipemomm** [comment]
It did the job. Thanks!
