### ISSUE TITLE
Update NuGet packages to reflect resolutions to issue14 & PR 15

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [paulcbetts/Fusillade#21]
Can the Nuget packages be updated to included the latest updates? This caused me issues with the enqueued failing requests with the RateLimitedHttpMessageHandler class.

**Comment by ghuntley** [comment]
@PhilipAnthonyMurray NuGet packages have been updated, apologies for the delay.

See https://github.com/paulcbetts/Fusillade/releases/tag/0.7.0 for release notes.
