### ISSUE TITLE
POST requests are being de-duplicated

### ISSUE THREAD

**Issue by kentcb** [paulcbetts/Fusillade#22]
Spurious POST requests are being de-duplicated. For me, this meant that only some data was being submitted to the server, and the rest was being silently dropped :(

I worked around this by sticking this at the start of `RateLimitedHttpMessageHandler.SendAsync`:

```C#
            if (request.Method == HttpMethod.Post)
            {
                return base.SendAsync(request, cancellationToken);
            }
```

I believe other methods should also be excluded from de-duplicating, such as PUT. If we can agree here on what methods should be excluded, and whether the above approach is fine, I'm happy to submit a PR.

**Comment by flagbug** [comment]
I think only `GET`, `HEAD`, `OPTIONS` and maaaybe `DELETE` requests should be de-duplicated, all others are not safe.

**Comment by ghuntley** [comment]
My vote is _only_ de-dupe retrieve actions i.e.  `GET`, `HEAD` & `OPTIONS`.

imho - any create (post), update (put) or delete (delete) should not be de-duped.

**Comment by ahmedalejo** [comment]
My vote is to only de-dupe entity-bodyless http method i.e. **GET**, **HEAD**, DELETE & OPTIONS.
