### ISSUE TITLE
Fusillade install failed due to Rx-Interfaces

### ISSUE THREAD

**Issue by cfl777** [paulcbetts/Fusillade#27]
Hi, 

I have tried to install Fusillade on a PCL (.NetPortable4.5), but it fails when installing dependency Rx-Interfaces 2.2.4. 

Tried multiple profiles: 7, 11, 259

Failure report:
`Error	 Could not install package 'Rx-Interfaces 2.2.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 0	`

**Comment by tameemansari** [comment]
In your nuget option select highest patch for dependency behavior which will resolve to Rx 2.2.5 and should install without issues.

**Comment by cfl777** [comment]
@tameemansari Thanks, its working correctly now.
