### ISSUE TITLE
Image request in Fusillade

### ISSUE THREAD

**Issue by sen3** [paulcbetts/Fusillade#5]
I am trying to the "Auto-deduplication of requests" feature on Fusillade. I try to fetch a same image 10 times. And it is sending 10 requests to the server. The url is same for all requests. Am I doing something wrong? 

Here is the sample test code:

```cs
 Uri u =  new Uri("http://www.brandeis.edu/about/images/newformat/map2.jpg");
 for (int i = 0; i < 10; i++)
  {
                HttpClient hc = new HttpClient(NetCache.UserInitiated);
                var s = await hc.GetAsync(u);

                var st = await s.Content.ReadAsStreamAsync();
}
```

**Comment by paulcbetts** [comment]
Because you're using `await`, you're guaranteeing that there is only one request in-flight at a time. Try collecting all of the returned Tasks without await then using `Task.WaitAll`
