### ISSUE TITLE
[Question] Do you only use Fussillade in Get methods or do Post/Delete etc also benefit?

### ISSUE THREAD

**Issue by promontis** [paulcbetts/Fusillade#6]
Hi Paul,

Small question regarding the use of Fussillade. Do you design your API client service POST/DELETE/etc methods also with a priority parameter? In other words, do you differentiate between background/user_initiated for non-GET methods?

I tend to think those non-GET methods should also be as quick as possible... so always user_initiated.

**Comment by paulcbetts** [comment]
POST/DELETEs don't get cached or deduped, but they can still be prioritized. Whether that makes sense depends on your app
