### ISSUE TITLE
Xamarin.iOS Warning MT3005 - System.Threading.Tasks dependency was not found

### ISSUE THREAD

**Issue by Corjuh** [paulcbetts/Fusillade#9]
After the Xamarin.iOS updates this week, I am receiving this compiler warning. It also manifests in weird run time crashes when the linker runs.

Full error text is below:

Warning MT3005: The dependency 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of the assembly 'Fusillade, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' was not found. Please review the project's references. (MT3005)

**Comment by paulcbetts** [comment]
Can you give me a stack of said weird runtime crashes?

**Comment by Corjuh** [comment]
Sorry; weirdness was caused by XS. Resetting that did the trick. Thanks.
